// ============= SHARED DATA SCHEMA =============
export const UserRole = ["customer", "admin", "driver"];
export const TripStatus = {
  PENDING: "pending",
  ASSIGNED: "assigned",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  IN_PROGRESS: "in-progress",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
};
export const VehicleType = ["bike", "auto", "car"];
export const DriverStatus = ["available", "busy", "offline"];

export const cities = [
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Surat",
];

// Distance matrix between cities (in km)
export const distances = {
  "Delhi-Mumbai": 1400,
  "Mumbai-Delhi": 1400,
  "Delhi-Bangalore": 2150,
  "Bangalore-Delhi": 2150,
  "Delhi-Chennai": 2180,
  "Chennai-Delhi": 2180,
  "Delhi-Kolkata": 1470,
  "Kolkata-Delhi": 1470,
  "Delhi-Hyderabad": 1570,
  "Hyderabad-Delhi": 1570,
  "Delhi-Pune": 1420,
  "Pune-Delhi": 1420,
  "Delhi-Ahmedabad": 950,
  "Ahmedabad-Delhi": 950,
  "Delhi-Jaipur": 280,
  "Jaipur-Delhi": 280,
  "Delhi-Surat": 1200,
  "Surat-Delhi": 1200,
  "Mumbai-Bangalore": 980,
  "Bangalore-Mumbai": 980,
  "Mumbai-Chennai": 1340,
  "Chennai-Mumbai": 1340,
  "Mumbai-Kolkata": 1960,
  "Kolkata-Mumbai": 1960,
  "Mumbai-Hyderabad": 710,
  "Hyderabad-Mumbai": 710,
  "Mumbai-Pune": 150,
  "Pune-Mumbai": 150,
  "Mumbai-Ahmedabad": 520,
  "Ahmedabad-Mumbai": 520,
  "Mumbai-Jaipur": 1150,
  "Jaipur-Mumbai": 1150,
  "Mumbai-Surat": 280,
  "Surat-Mumbai": 280,
  "Bangalore-Chennai": 350,
  "Chennai-Bangalore": 350,
  "Bangalore-Kolkata": 1870,
  "Kolkata-Bangalore": 1870,
  "Bangalore-Hyderabad": 570,
  "Hyderabad-Bangalore": 570,
  "Bangalore-Pune": 840,
  "Pune-Bangalore": 840,
  "Bangalore-Ahmedabad": 1470,
  "Ahmedabad-Bangalore": 1470,
  "Bangalore-Jaipur": 1780,
  "Jaipur-Bangalore": 1780,
  "Bangalore-Surat": 1200,
  "Surat-Bangalore": 1200,
  "Chennai-Kolkata": 1670,
  "Kolkata-Chennai": 1670,
  "Chennai-Hyderabad": 630,
  "Hyderabad-Chennai": 630,
  "Chennai-Pune": 1180,
  "Pune-Chennai": 1180,
  "Chennai-Ahmedabad": 1800,
  "Ahmedabad-Chennai": 1800,
  "Chennai-Jaipur": 2100,
  "Jaipur-Chennai": 2100,
  "Chennai-Surat": 1530,
  "Surat-Chennai": 1530,
  "Kolkata-Hyderabad": 1500,
  "Hyderabad-Kolkata": 1500,
  "Kolkata-Pune": 1810,
  "Pune-Kolkata": 1810,
  "Kolkata-Ahmedabad": 2040,
  "Ahmedabad-Kolkata": 2040,
  "Kolkata-Jaipur": 1350,
  "Jaipur-Kolkata": 1350,
  "Kolkata-Surat": 1870,
  "Surat-Kolkata": 1870,
  "Hyderabad-Pune": 560,
  "Pune-Hyderabad": 560,
  "Hyderabad-Ahmedabad": 1270,
  "Ahmedabad-Hyderabad": 1270,
  "Hyderabad-Jaipur": 1300,
  "Jaipur-Hyderabad": 1300,
  "Hyderabad-Surat": 1000,
  "Surat-Hyderabad": 1000,
  "Pune-Ahmedabad": 670,
  "Ahmedabad-Pune": 670,
  "Pune-Jaipur": 1270,
  "Jaipur-Pune": 1270,
  "Pune-Surat": 430,
  "Surat-Pune": 430,
  "Ahmedabad-Jaipur": 680,
  "Jaipur-Ahmedabad": 680,
  "Ahmedabad-Surat": 240,
  "Surat-Ahmedabad": 240,
  "Jaipur-Surat": 920,
  "Surat-Jaipur": 920,
};

// Vehicle rates per km in INR - Updated for bike, auto, car with sub-options
export const vehicleRates = {
  "bike-economy": 5,
  "bike-premium": 8,
  "bike-sport": 12,
  "auto-standard": 10,
  "auto-ac": 15,
  "auto-premium": 20,
  "car-hatchback": 15,
  "car-sedan": 25,
  "car-suv": 35,
};

export const vehicleLabels = {
  "bike-economy": "Bike - Economy (₹5/km)",
  "bike-premium": "Bike - Premium (₹8/km)",
  "bike-sport": "Bike - Sport (₹12/km)",
  "auto-standard": "Auto - Standard (₹10/km)",
  "auto-ac": "Auto - AC (₹15/km)",
  "auto-premium": "Auto - Premium (₹20/km)",
  "car-hatchback": "Car - Hatchback (₹15/km)",
  "car-sedan": "Car - Sedan (₹25/km)",
  "car-suv": "Car - SUV (₹35/km)",
};

export const vehicleCategories = {
  bike: [
    { key: "bike-economy", label: "Economy", rate: 5 },
    { key: "bike-premium", label: "Premium", rate: 8 },
    { key: "bike-sport", label: "Sport", rate: 12 },
  ],
  auto: [
    { key: "auto-standard", label: "Standard", rate: 10 },
    { key: "auto-ac", label: "AC", rate: 15 },
    { key: "auto-premium", label: "Premium", rate: 20 },
  ],
  car: [
    { key: "car-hatchback", label: "Hatchback", rate: 15 },
    { key: "car-sedan", label: "Sedan", rate: 25 },
    { key: "car-suv", label: "SUV", rate: 35 },
  ],
};
